services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    environment:
      - 'MYSQL_DATABASE=live_alone'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=admin'
    ports:
      - '3307:3306'
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - '6378:6379'
  kafka:
    image: 'apache/kafka:3.7.1'
    container_name: kafka
    ports:
      - "9092:9092"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - 'MONGO_INITDB_DATABASE=chatdb'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=verysecret'



