spring:
  application:
    name: livealone
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-43-201-46-108.ap-northeast-2.compute.amazonaws.com/live_alone
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6378
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@ec2-43-201-46-108.ap-northeast-2.compute.amazonaws.com/chatdb?authSource=admin
      port: 27017


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  jackson:
    property-naming-strategy: SNAKE_CASE


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SOCIAL_GOOGLE_CLIENT_ID}
            client-secret: ${SOCIAL_GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
          naver:
            client-id: ${SOCIAL_NAVER_CLIENT_ID}
            client-secret: ${SOCIAL_NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - email
            client-name: Naver
          kakao:
            client-id: ${SOCIAL_KAKAO_CLIENT_ID}
            client-secret: ${SOCIAL_KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            provider: kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
    consumer:
      bootstrap-servers: 127.0.0.1:9092
jwt:
  key: ${JWT_SECRET_KEY}
  access-expire-time: ${ACCESS_EXPIRE_TIME}
  refresh-expire-time: ${REFRESH_EXPIRE_TIME}


server:
  port: 8080

kakao:
  pay:
    cid: TC0ONETIME
    secret: DEV1983009FCE70023372B535B4EB027DEB9824F
    approval-url: http://localhost:8080/completePayment
    cancel-url: http://localhost:8080/payment
    fail-url: http://localhost:8080/payment

toss:
  api:
    base-url : http://seoldarin.iptime.org:7956
    client-key: test_ck_kYG57Eba3GPyQ4zAdxQkVpWDOxmA
    secret-key: test_sk_jExPeJWYVQ1ekabzNRlxV49R5gvN
    ret-url: /completePayment
    ret-cancel-url: /payment
    result-callback: /completePayment

