name: livealone-test

on:
  push:
    # 배열로 여러 브랜치를 넣을 수 있다.
    branches: [ develop ]
    # github pull request 생성시
  pull_request:
    branches:
      - develop # -로 여러 브랜치를 명시하는 것도 가능
      

env:
  DOCKER_IMAGE_TAG_NAME: livealone

jobs:
  build-and-docker-push:
    runs-on: ubuntu-22.04 # 실행환경

    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      # java version 지정
      - name: Set up JDK 17 with OpenJDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest

  deploy-to-ec2:
    needs: build-and-docker-push # 위의 build-and-docker-push이 끝나고 실행
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            CONTAINER_ID=$(sudo docker ps -q --filter "publish=8080-8080")
            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi
            # 여기서의 환경 변수도 여러분 상황에 맞게 작성하시면 됩니다!!!
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest
            sudo docker run -d -p 8080:8080 \
                -e MYSQL_USER=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
                -e MYSQL_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
                -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest \
                -e ACCESS_EXPIRE_TIME=${{ secrets.ACCESS_EXPIRE_TIME }} \
                -e REFRESH_EXPIRE_TIME=${{ secrets.REFRESH_EXPIRE_TIME }} \
                -e SOCIAL_GOOGLE_CLIENT_ID=${{ secrets.SOCIAL_GOOGLE_CLIENT_ID }} \
                -e SOCIAL_GOOGLE_CLIENT_SECRET=${{ secrets.SOCIAL_GOOGLE_CLIENT_SECRET }} \
                -e SOCIAL_NAVER_CLIENT_ID=${{ secrets.SOCIAL_NAVER_CLIENT_ID }} \
                -e SOCIAL_NAVER_CLIENT_SECRET=${{ secrets.SOCIAL_NAVER_CLIENT_SECRET }} \
                -e SOCIAL_KAKAO_CLIENT_ID=${{ secrets.SOCIAL_KAKAO_CLIENT_ID }} \
                -e SOCIAL_KAKAO_CLIENT_SECRET=${{ secrets.SOCIAL_KAKAO_CLIENT_SECRET }} \
                -e MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} \
                -e MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} 
                
